config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    devise_for :admin_users, controllers: {
      sessions: 'admin/admin_users/sessions',
    }
    resources :users do
      collection do
        get :reports
      end

      member do
        get :collections
        get :approve
        get :deny
        get :enable
        get :verify
      end
    end
    resources :categories
    resources :fees
    resources :featured_users, except: [:edit, :update]
    resources :featured_collections, except: [:edit, :update]
    resources :transactions, only: [:index]

    get 'dashboard', to: 'dashboard#index'
    get 'change_network', to: 'dashboard#change_network'
    root to: 'dashboard#index'
  end

  resources :users, except: [:index, :create, :destroy] do
    collection do
      get :following
      get :follow
      get :unfollow
      get :load_tabs
      post :like
      post :unlike
      post :bid
      post :report
      post :create_contract
    end
  end
  resources :collections, only: [:new, :show, :create]  do
    member do
      get :remove_from_sale
      get :fetch_details
      get :fetch_transfer_user
      post :bid
      post :buy
      post :sell
      post :update_token_id
      post :change_price
      post :transfer_token
      post :sign_metadata_hash
      post :sign_metadata_with_creator
      post :sign_fixed_price
      post :approve
      post :owner_transfer
      post :mystery_box_transfer
      post :update_owner_transfer_mystery
      post :burn
      post :save_contract_nonce_value
      post :get_nonce_value
      post :save_nonce_value
      post :get_contract_sign_nonce
    end
  end

  resources :sessions, only: [:create, :destroy] do
    collection do
      get :valid_user
    end
  end
  resources :likes, only: [:create, :update]
  resources :bids
  resources :fees

  ### CUSTOM ROUTES
  get 'dashboard', to: 'dashboard#index'
  get 'change_network', to: 'dashboard#change_network'
  get 'top_buy_sell', to: 'dashboard#top_buyers_and_sellers'
  get 'my_items', to: 'users#my_items'
  get 'activities', to: 'activities#index'
  get 'load_more_activities', to: 'activities#load_more'
  get 'search', to: 'dashboard#search'
  get 'notifications', to: 'dashboard#notifications'
  get 'contract_abi', to: 'dashboard#contract_abi'
  get 'category_filter', to: 'dashboard#set_categories_by_filter'
  get 'gas_price', to: 'dashboard#gas_price'

  ### STATIC PAGES
  get 'about', to: 'static#about'
  get 'faq', to: 'static#faq'
  get 'terms_conditions', to: 'static#terms_conditions'
  get 'privacy', to: 'static#privacypolicy'
  get 'sitemap', to: 'static#sitemap', defaults: {format: 'xml' }

  ### ROOT PAGE
  root to: "dashboard#index"

  ### THIRD-PARTY ROUTES
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/featured_user.rb
class FeaturedUser < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/featured_users_controller.rb
class Admin::FeaturedUsersController < Admin::BaseController
  before_action :is_maxed_out, only: :new

  def index
    @featured_users = FeaturedUser.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find_by_address(params[:id])
    @errors = ["Given User ID is invalid"] unless @user.present? 
    # data = user.present? ? {name: user.name, img: user.profile_image} : {}
    # render json: {data: data} 
  end

  def new
  end

  def create
    @featured_user = FeaturedUser.new(featured_user_params)

    if featured_user_params[:user_id].present?
      featured_user_params[:user_id].split(",").each do |user_id|
        FeaturedUser.find_or_create_by(user_id: user_id)
      end
    else
      @errors = ["User ID must present"]
    end

    if @featured_user.valid?
    else
    end
  end

  def destroy
    featured_user = FeaturedUser.find(params[:id])
    featured_user.destroy

    respond_to do |format|
      format.html { redirect_to admin_featured_users_url, notice: "Featured User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def featured_user_params
    params.require(:featured_user).permit(:user_id)
  end

  def is_maxed_out
    @featured_users = FeaturedUser.all
    if @featured_users.count >= 5
      redirect_to admin_featured_users_url, alert: "Already created 5 featured users. Please destroy some to create new"
    end
  end
end

app/views/admin/featured_users/_featured_user.html.erb
<div class="my-explore-div featured-user-entry">
  <div class="box-explore-bids">
    <div class="explore-bids-img" style="background-image: url(<%= url_for(@user.profile_image) %>);">
      <%= image_tag url_for(@user.profile_image), class: "img-responsive" %>
    </div>
    <div class="explore-bid-opt-img">
    </div>

    <div class="explore-bids-content">
      <h4><%= @user.name %></h4>
      <p><b><%= @user.address %></b></p>
    </div>
    <div class="remove-button">
      <button class="btn btn-sm featured-user-remove btn-danger" data-id="<%= @user.id %>" type="button"><%= t('shared.delete')%> <i class="far fa-trash-alt"></i></button>
    </div>
  </div>
</div>

app/views/admin/featured_users/create.js.erb
<% if @errors.present? %>
  <%= custom_error_flash(@errors, 'error') %>
<% else %>
  <% flash.keep[:notice] = 'Featured Users Successfully created.' %>
  window.location.replace("<%= admin_featured_users_path %>");
<% end %>

app/views/admin/featured_users/index.html.erb
<div class="main-content">
  <div class="page-content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="page-title-box d-flex align-items-center justify-content-between">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-6">
                  <h4 class="card-title"><%= t("admin.featured_users.index.title") %></h4>
                </div>
                <div class="col-sm-2"></div>
                <div class="col-sm-4">
                  <%= link_to t("admin.featured_users.index.add_new"), new_admin_featured_user_path, class: "float-right" %>
                </div>
              </div>
              <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                <thead>
                  <tr>
                    <!-- <th><%#= t("admin.featured_users.index.id") %></th> -->
                    <th><%= t("admin.featured_users.index.name") %></th>
                    <th><%= t("admin.featured_users.index.address") %></th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <% if @featured_users.present? %>
                    <% @featured_users.each do |fuser| %>
                      <tr>
                        <!-- <td><%#= fuser.id %></td> -->
                        <td><%= fuser.user.name %></td>
                        <td><%= fuser.user.address %></td>
                        <td>
                          <%= link_to t('shared.destroy'), admin_featured_user_path(fuser), method: :delete, class: "pr-2" %>
                        </td>
                      </tr>
                    <% end %>
                  <% else %>
                    <tr>
                      <td colspan="4"><%= t(:no_records, scope: :admin) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          <div class="flickr_pagination">
            <%= will_paginate @featured_users %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/featured_users/new.html.erb
<div class="main-content">
  <div class="page-content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <div class="card">
          <%= form_tag(admin_featured_users_path, method: :post, remote: true, multipart: true) do %>
          <div class="card-body">
            <h4 class="card-title"><%= t('admin.featured_users.form.title') %></h4>

            <div class="form-group row">
              <label for="example-text-input" data-count="<%= 5 - @featured_users.count %>" class="col-md-2 users-total-count col-form-label">Only Left <%= 5 - @featured_users.count %></label>
            </div>

            <div class="form-group row">
              <label for="example-text-input" class="col-md-2 col-form-label"><%= t("admin.featured_users.form.search_user") %></label>
              <div class="col-md-8">
                <%= text_field_tag 'user_id', nil, class: 'form-control input-custom', placeholder: t('admin.featured_users.form.search_user_label') %>
              </div>
              <div class="col-md-2">
                <a class="btn btn-primary show-selected-user"><%= t('shared.add')%></a>
              </div>
            </div>
            <%= hidden_field_tag 'featured_user[user_id]', nil, class: 'form-control custom-user-id-input' %>

            <div class="row featured-users-list">
            </div>

            <div class="form-group row">
              <label for="example-number-input" class="col-md-2 col-form-label"></label>
              <div class="col-md-10">
                <button type="submit" class="btn btn-primary mr-1 w-md"><%= t('shared.submit')%></button>
                <%= link_to t('shared.cancel'), admin_featured_users_path, class: "btn btn-secondary w-md add_btn" %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/featured_users/show.js.erb
<% if @errors.present? %>
  <%= custom_error_flash(@errors, 'error') %>
<% else %>
  var addedList = $(".custom-user-id-input").val().split(",")
  $("#user_id").val("")

  if (addedList[0] !== "" && addedList.includes("<%= @user.id %>")) {
    toastr.error("User already added to the list");
  } else {
    var totalCount = parseInt($(".users-total-count").data("count"));
    totalCount -= 1
    $(".users-total-count").data("count", totalCount)
    $(".users-total-count").text('Only Left '+totalCount)
    $('.featured-users-list').append('<%= j(render "featured_user") %>');

    if ($(".custom-user-id-input").val() === "") {
      $(".custom-user-id-input").val("<%= @user.id %>")
    } else {
      var val = $(".custom-user-id-input").val()
      val += "," + "<%= @user.id %>"
      $(".custom-user-id-input").val(val)
    }
  }
<% end %>