config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    devise_for :admin_users, controllers: {
      sessions: 'admin/admin_users/sessions',
    }
    resources :users do
      collection do
        get :reports
      end

      member do
        get :collections
        get :approve
        get :deny
        get :enable
        get :verify
      end
    end
    resources :categories
    resources :fees
    resources :featured_users, except: [:edit, :update]
    resources :featured_collections, except: [:edit, :update]
    resources :transactions, only: [:index]

    get 'dashboard', to: 'dashboard#index'
    get 'change_network', to: 'dashboard#change_network'
    root to: 'dashboard#index'
  end

  resources :users, except: [:index, :create, :destroy] do
    collection do
      get :following
      get :follow
      get :unfollow
      get :load_tabs
      post :like
      post :unlike
      post :bid
      post :report
      post :create_contract
    end
  end
  resources :collections, only: [:new, :show, :create]  do
    member do
      get :remove_from_sale
      get :fetch_details
      get :fetch_transfer_user
      post :bid
      post :buy
      post :sell
      post :update_token_id
      post :change_price
      post :transfer_token
      post :sign_metadata_hash
      post :sign_metadata_with_creator
      post :sign_fixed_price
      post :approve
      post :owner_transfer
      post :mystery_box_transfer
      post :update_owner_transfer_mystery
      post :burn
      post :save_contract_nonce_value
      post :get_nonce_value
      post :save_nonce_value
      post :get_contract_sign_nonce
    end
  end

  resources :sessions, only: [:create, :destroy] do
    collection do
      get :valid_user
    end
  end
  resources :likes, only: [:create, :update]
  resources :bids
  resources :fees

  ### CUSTOM ROUTES
  get 'dashboard', to: 'dashboard#index'
  get 'change_network', to: 'dashboard#change_network'
  get 'top_buy_sell', to: 'dashboard#top_buyers_and_sellers'
  get 'my_items', to: 'users#my_items'
  get 'activities', to: 'activities#index'
  get 'load_more_activities', to: 'activities#load_more'
  get 'search', to: 'dashboard#search'
  get 'notifications', to: 'dashboard#notifications'
  get 'contract_abi', to: 'dashboard#contract_abi'
  get 'category_filter', to: 'dashboard#set_categories_by_filter'
  get 'gas_price', to: 'dashboard#gas_price'

  ### STATIC PAGES
  get 'about', to: 'static#about'
  get 'faq', to: 'static#faq'
  get 'terms_conditions', to: 'static#terms_conditions'
  get 'privacy', to: 'static#privacypolicy'
  get 'sitemap', to: 'static#sitemap', defaults: {format: 'xml' }

  ### ROOT PAGE
  root to: "dashboard#index"

  ### THIRD-PARTY ROUTES
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/common/_change_network.erb
<div class="header__action header__action--profile network-dropdown">
    <a class="header__profile-btn header__profile-btn--verified" href="javascript:void(0);" role="button" id="dropdownMenuProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= Current.network.name%>
      <i class="fas fa-chevron-down"></i>
    </a>

    <ul class="dropdown-menu header__profile-menu" aria-labelledby="dropdownMenuProfile">
        <% Network.all.each do |network| %>
            <li><a class="dropdown-item" href="<%= "/change_network/?chain_id=#{network.chain_id}"%>"><%= network.name %></a></li>
        <%end%>
    </ul>
</div>

app/views/common/_collection_card.html.erb
<% if current_user %>
  <%= react_component("collections/like", address: current_user.address, isLiked: collection.isLiked?(current_user.id), collectionId: collection.id) %>
<% else %>
  <div class="explore-bids-icon-heart no-wishlist">
    <i class="fa fa-heart"></i>
  </div>
<% end %>

<%= link_to collection_path(collection.address) do %>
  <div class="explore-bids-img" style="background-image: url('<%= cover_url(collection) %>');">
    <%= image_tag cover_url(collection), class: "img-responsive" %>
  </div>
<% end %>

<div class="explore-bid-opt-img">
  <%= render partial: 'common/collection_owner_imgs', locals: {collection: collection} %>

  <div class="explore-bid-opt-icon">
    <div class="dropdown">
      <div class="more-list dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-ellipsis-v"></i>
      </div>
      <ul class="dropdown-menu">
        <% if collection.instant_sale_enabled %><li><%= link_to t('shared.buy_now'), collection_path(collection.address), anchor: '#Buy-modal' %></li><% end %>
        <% if collection.put_on_sale %><li><a href="<%= collection_path(collection.address) %>"><%= t('collections.show.place_a_bid')%></a></li><% end %>
        <li><a href="#"><%= t('collections.show.report')%></a></li>
      </ul>
    </div>
  </div>
</div>
<div class="explore-bids-content">
  <div>
    <h4><%= collection.title %></h4>
    <p><%= collection.title_desc %></p>
  </div>
  <% if collection.max_bid %>
    <p class="bid_status">Highest bid <b><%= collection.max_bid.value %></b></p>
  <% end %>
</div>

app/views/common/_empty.html.erb
<div class="no-details" style="">
  <h3 class="color-grey"><%= t('shared.no_data_found')%></h3>
</div>

app/views/common/_empty_activity.html.erb
<div class="activity dummy-activity">
        <a class="activity__cover" href="javascript:void(0);">
            <img src="/assets/banner-bg.jpeg" width="140" height="162">
</a>      <div class="activity__content">
        <h3 class="activity__title">
            <a href="javascript:void(0);">
                <%= t('collections.collection_name')%>
</a>
        </h3>
        <p class="activity__text"><%= t('collections.liked_by')%>
          <a href="javascript:void(0);">
              @User name
          </a>  <br>
          <span class="activity__time">about 2 hours </span>
      </p></div>
    </div>

app/views/common/_empty_card_collection.html.erb
<div class="card dummy-explorer">
    <div class="t_c">
        <a href="javascript:void(0);" class="card__cover">
            <span class="collection-card-img" style="background-image: url('/assets/banner-bg.jpeg')">
                <img src="/assets/banner-bg.jpeg" />
            </span>
        </a>
        <button class="card__likes heart is-active"><i class="far fa-heart"></i><i class="fas fa-heart"></i><span>1</span></button>
    </div>
    <h3 class="card__title" data-toggle="tooltip" data-placement="top" title="" data-original-title="Image New 003 / 1 of 1">
        <a href="javascript:void(0);"><%= t('collections.collection_name')%></a>
    </h3>
    <div class="card__author">
        <img src="/assets/default_user.png">
        <a href="javascript:void(0);">@0x00aeccc...daf0</a>
    </div>
    <div class="card__info">
        <div class="card__price">
            <span><%= t('shared.reserve_price')%></span>
            <span>0.00001 ETH</span> 
        </div>
    </div>
</div>

app/views/common/_empty_topbuyers.html.erb
<li class="col-12 col-sm-6 col-md-4 col-lg-3 dummy-topbuyer">
    <div class="sellers-list__author sellers-list__author--verified">
    <img src="/assets/default_user.png">
    <span class="sellers-list__number">1</span>
    <a href="javascript:void(0)">0xad00de4...485d</a>
    <span data-toggle="tooltip" data-placement="top" title="" data-original-title=""></span>
    </div>
</li>

app/views/common/_footer.html.erb
<!-- end get started -->
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 order-1 order-md-1 order-lg-1 order-xl-1">
              <%= image_tag Rails.application.credentials.config[:app_header_logo], class: 'img-responsive logo-img' %>
        <p class="footer__tagline">
          <%= t('footer.tag_line', app_name: Rails.application.credentials.config[:app_name]) %>
        </p>
      </div>

      <div class="col-6 col-md-3 col-lg-3 col-xl-3 order-2 order-md-2 order-lg-2 order-xl-2 offset-md-0 offset-lg-0">
        <h6 class="footer__title"><%= Rails.application.credentials.config[:app_name] %> <%= t('footer.marketplace') %> </h6>
        <div class="footer__nav">
         <!--  <a href="/about"><%= t('footer.about') %> <%= Rails.application.credentials.config[:app_name] %> </a> -->
           <a href="/about"><%= t('footer.about') %> Yolospace </a>
          <!--   <a target="_blank" href="/terms_conditions">Terms and Conditions</a> -->
       <!--   <a target="_blank" href="/privacy">Privacy</a> -->
          <!--          <a href="/sitemap">Sitemap</a>-->
        </div>
      </div>

      <div class="col-6 col-md-3 col-lg-3 col-xl-3 order-3 order-lg-3 order-md-3 order-xl-4">
        <!--   <h6 class="footer__title">Community</h6> -->
        <div class="footer__nav">
          <!--  <a href="<%= Rails.application.credentials.config[:support_url] %>" target="_blank">Help Center</a> -->
          <!--  <a href="<%= Rails.application.credentials.config[:discussion_url] %>" target="_blank">Discussion</a> -->
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <div class="footer__content">
          <div class="footer__social">
            <a href="https://www.facebook.com/yolonftasia/" target="_blank" data-toggle="tooltip" title="Facebook"><i class="fab fa-facebook-f"></i></a>
            <a href="https://twitter.com/yolospaceglobal" target="_blank" data-toggle="tooltip" title="Twitter"><i class="fab fa-twitter"></i></a>
            <a href="https://t.me/+nel3insT59ExMDhl" target="_blank" data-toggle="tooltip" title="Telegram"><i class="fab fa-telegram-plane"></i></a>
            
            <a href="https://www.instagram.com/yolospace_asia/" target="_blank" data-toggle="tooltip" title="Asia Instagram"><i class="fab fa-instagram"></i></a>
            <a href="https://www.instagram.com/yolospace_global/" target="_blank" data-toggle="tooltip" title="Global Instagram"><i class="fab fa-instagram"></i></a>

            <a href="https://www.pinterest.com/YOLOSPACE_IO/" target="_blank" data-toggle="tooltip" title="Pinterest"><i class="fab fa-pinterest"></i></a>

            <a href="https://www.youtube.com/channel/UCXmcJmfo35ULnoQ9H6Veu4Q" target="_blank" data-toggle="tooltip" title="YouTube"><i class="fab fa-youtube"></i></a>
            
            <a href="https://discord.com/invite/gvPxv7SsaK" target="_blank" data-toggle="tooltip" title="Discord">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512" fill="#fff"><path d="M524.531,69.836a1.5,1.5,0,0,0-.764-.7A485.065,485.065,0,0,0,404.081,32.03a1.816,1.816,0,0,0-1.923.91,337.461,337.461,0,0,0-14.9,30.6,447.848,447.848,0,0,0-134.426,0,309.541,309.541,0,0,0-15.135-30.6,1.89,1.89,0,0,0-1.924-.91A483.689,483.689,0,0,0,116.085,69.137a1.712,1.712,0,0,0-.788.676C39.068,183.651,18.186,294.69,28.43,404.354a2.016,2.016,0,0,0,.765,1.375A487.666,487.666,0,0,0,176.02,479.918a1.9,1.9,0,0,0,2.063-.676A348.2,348.2,0,0,0,208.12,430.4a1.86,1.86,0,0,0-1.019-2.588,321.173,321.173,0,0,1-45.868-21.853,1.885,1.885,0,0,1-.185-3.126c3.082-2.309,6.166-4.711,9.109-7.137a1.819,1.819,0,0,1,1.9-.256c96.229,43.917,200.41,43.917,295.5,0a1.812,1.812,0,0,1,1.924.233c2.944,2.426,6.027,4.851,9.132,7.16a1.884,1.884,0,0,1-.162,3.126,301.407,301.407,0,0,1-45.89,21.83,1.875,1.875,0,0,0-1,2.611,391.055,391.055,0,0,0,30.014,48.815,1.864,1.864,0,0,0,2.063.7A486.048,486.048,0,0,0,610.7,405.729a1.882,1.882,0,0,0,.765-1.352C623.729,277.594,590.933,167.465,524.531,69.836ZM222.491,337.58c-28.972,0-52.844-26.587-52.844-59.239S193.056,219.1,222.491,219.1c29.665,0,53.306,26.82,52.843,59.239C275.334,310.993,251.924,337.58,222.491,337.58Zm195.38,0c-28.971,0-52.843-26.587-52.843-59.239S388.437,219.1,417.871,219.1c29.667,0,53.307,26.82,52.844,59.239C470.715,310.993,447.538,337.58,417.871,337.58Z"/></svg>         
            </a>
          </div>

          <small class="footer__copyright">© Yolospace, 2022</small>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/common/_header_top.html.erb
<div class="header__top">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="top_menu">
            <ul>
              <li><a href="<%= Rails.application.credentials.config[:support_url] %>" target="_blank">><%= t('header.help_center') %></a></li>
              <li><a href="<%= Rails.application.credentials.config[:discussion_url] %>" target="_blank">><%= t('footer.discussion') %></a></li>
            </ul>
          </div>
        </div>
        <!--<div class="col-lg-6 col-md-6 col-sm-6">-->
          <!--<div class="head__lang">-->
            <!--<a class="head__lang-btn" href="javascript:void(0);" role="button" id="dropdownLang" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
              <!--<img src="img/flags/uk.svg" alt="">-->
              <!--<span>English</span>-->
            <!--</a>-->
            <!--<ul class="dropdown-menu head__lang-dropdown" aria-labelledby="dropdownLang">-->
              <!--<li><a href="javascript:void(0);"><img src="img/flags/spain.svg" alt=""><span>Spanish</span></a></li>-->
              <!--<li><a href="javascript:void(0);"><img src="img/flags/russia.svg" alt=""><span>Russian</span></a></li>-->
              <!--<li><a href="javascript:void(0);"><img src="img/flags/china.svg" alt=""><span>Chinese</span></a></li>-->
            <!--</ul>-->
          <!--</div>-->
        <!--</div>-->
      </div>
    </div>
  </div>

app/views/common/_meta_og_html.erb
<% content_for :meta_og do %>
  <meta property="og:title" content="<%= title %>" />
  <meta property="og:description" content="<%= description %>" />
  <meta property="og:image" content="<%= image %>" />
  <meta property="og:url" content="<%= current_url %>" />
  <meta property="og:type" content="website">
  <meta property="og:image:width" content="600" />
  <meta property="og:image:height" content="400" />

  <meta name="twitter:card" content="summary" />
  <meta property="twitter:domain" content="<%= get_host_without_www(current_url) %>">
  <meta name="twitter:title" content="<%= title %>"/>
  <meta name="twitter:description" content="<%= description %>"/>
  <meta name="twitter:image" content="<%= image %>"/>

  <meta property="og:title" content="spot where the warmth of NFTs sets a new path of lucrative avenues"/>

<meta property="og:description" content="Yolospace is the 1st ESG Community based NFT marketplace"/>
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="/"/>
<meta name="twitter:title" content="A spot where the warmth of NFTs sets a new path of lucrative avenues"/>
<meta name="twitter:description" content="Yolospace is the 1st ESG Community based NFT marketplace"/>
<meta name="twitter:image" content=" ( Image url )"/>
<% end %>

app/views/common/_my_header.html.erb
<header class="header">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="header__content">
          
          <div class="header__logo filled-flex-custom">
            <a href="<%= root_path %>">
              <%= image_tag Rails.application.credentials.config[:app_header_logo], class: 'img-responsive' %>
            </a>
            <div class="mobile-network">
              <%= render partial: 'common/change_network' %>
            </div>
          </div>
          
          <%= render "common/search" %>
          <%= render "common/static_nav" %>

          <div class="header__actions">
            <div class="header__action header__action--search">
              <button class="header__action-btn" type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/></svg></button>
            </div>

            <div class="dropdown desktop-notification">
              <a data-toggle="dropdown" class="view-notification" href="javascript:void(0);" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-bell"></i>
                <p class="notification_count"><%= Notification.unread(current_user).count %></p>
              </a>
              <div class="dropdown-menu header__profile-menu ">
              <h4 class="heading">
                <!-- <i class="fa fa-bell"></i>&nbsp; -->
                <%= t('header.notifications') %>
              </h4>
                <ul class="user-notification-list"></ul>
              </div>
            </div>

            <div class="header__action header__action--profile">
              <a class="header__profile-btn" href="javascript:void(0);" role="button" id="dropdownMenuProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= image_tag url_for(current_user.profile_image), class: "img-responsive" %>
                    <% if current_user.is_verified %>
                        <i class="fa fa-check-circle" aria-hidden="true"></i>
                    <% end %>
                    <div><p><%= current_user.full_name %></p>
                    <span class="header-current-balance"><%#= current_balance %> <%#= Rails.application.credentials.send(Current.network.short_name)[:base_coin] %></span></div>
                    <i class="fas fa-chevron-down"></i>
              </a>

              <ul class="dropdown-menu header__profile-menu" aria-labelledby="dropdownMenuProfile">
                <li><a href="<%=my_items_path%>"><i class="far fa-user"></i><span><%= t('header.profile') %></span></a></li>
                <li><a href="<%=edit_user_path(current_user)%>"><i class="fas fa-cog"></i><span><%= t('header.settings') %></span></a></li>
                <li><a href="<%= activities_path(activity_type: "activity") %>"><i class="fas fa-list"></i> <span><%= t('header.activity') %></span></a></li>
                <li><a href="javascript:void(0);" onclick="window.disconnect(<%= current_user.address %>)"><i class="fas fa-sign-out-alt"></i> <span><%= t('header.sign_out') %></span></a></li>
              </ul>
            </div>

            <%#= render partial: 'common/language_select' %>
            <!-- <div class="desktop-network">
              <%#= render partial: 'common/change_network' %>
            </div> -->
            
            <button class="header__btn" type="button">
              <span></span>
              <span></span>
              <span></span>
            </button>
          </div>


        </div>
      </div>
    </div>
  </div>
</header>

<script type="text/javascript">
    var address = "<%= current_user.address %>"

    $(document).ready(function () {
        window.loadUser(address)
    })
</script>

app/views/common/_search.html.erb
       <%= form_tag search_path, :method => :get ,:class=> "header__search" do %>
        <input type="text" name="query"   value="<%=params[:query]%>" placeholder="<%= t('header.search_placeholder') %>">
        <button type="search"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/></svg></button>
        <button type="button" class="close"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M13.41,12l6.3-6.29a1,1,0,1,0-1.42-1.42L12,10.59,5.71,4.29A1,1,0,0,0,4.29,5.71L10.59,12l-6.3,6.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0L12,13.41l6.29,6.3a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42Z"></path></svg></button>

        
      <%end%>

app/views/common/_static_nav.html.erb
 <div class="header__menu">
        <ul class="header__nav">
          <li class="header__nav-item">
            <a class="header__nav-link" href="/faq"><%= t('header.HIW') %></a>
          </li>
          <li class="header__nav-item">
            <a class="header__nav-link" href="/about"><%= t('header.about_us') %></a>
          </li>
          <li class="header__nav-item">
             <%#if current_user.is_approved%>
                  <a href="<%=new_collection_path%>" class="header__nav-link"><%= t('header.create') %></a>
             <%#end%>
          </li>
          <li class="header__nav-item">
            <a href="<%= activities_path(activity_type: "activity") %>" class="header__nav-link"><%= t('header.activity') %></a>
          </li>
          <!--<li class="header__nav-item">
            <a href="#" class="header__nav-link">Community</a>
          </li>-->
        </ul>
      </div>

app/views/common/_user_balance.html.erb
<a class="dropdown-toggle profile-section" data-toggle="dropdown" href="javascript:void(0);">
  <div class="profile-list">
    <div class="profile-list-img">
      <%= image_tag url_for(current_user.profile_image(:thumb)), class: "img-responsive" %>
      <% if current_user.is_verified %>
        <i class="fa fa-check-circle" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class="profile-list-content">
      <h5><span class="curBalance"><%= current_balance %></span> <%= Rails.application.credentials.send(Current.network.short_name)[:base_coin] %></h5>
      <p class="para-color"><%= current_user.masked_address %></p>
    </div>
    <div class="profile-list-icon">
      <i class="fa fa-angle-down"></i>
    </div>
  </div>
</a>

app/views/common/_wallet_connect.html.erb
<div id="connect_to_wallet" class="zoom-anim-dialog mfp-hide modal sm_modal">
  <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button>
  <h4><%= t('header.connect_wallet') %></h4>
  <p><%= t('header.wallet_help') %> <a href="#what-wallet" class="open-modal"><%= t('header.wallet_info') %></a></p>

  <div class="w_btn">
    <a href="javascript:void(0);" onclick="window.connect('metamask')">
      <span class="w_btn_icon"><img src="/assets/metamask.png"></span>
      <%= t('header.metamask_wallet') %>
    </a>
    <a href="javascript:void(0);" onclick="window.connect('walletConnect')">
      <span class="w_btn_icon"><img src="/assets/wallet.png"></span>
      WalletConnect &nbsp; &nbsp;
    </a>
  </div>
  <p class="mt-20"><%= t('header.wallet_confi') %></p>
</div>


<div id="what-wallet" class="zoom-anim-dialog mfp-hide modal sm_modal">
  <!-- <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button> -->
  <a class="open-modal default-modal-element" href="#connect_to_wallet">
    <i class="fas fa-times"></i>
  </a>
  <h4 class="modal-title">What is a wallet?</h4>
  <p>Wallets are used to send, receive, and store digital assets like Ether. Wallets come in many forms. They are either built into your browser, an extension added to your browser, a piece of hardware plugged into your computer, or even an app on your phone.</p>
</div>


<script type="text/javascript">
  $('#text-what-is-wallet').click(function(){
    $("#connect_to_wallet .modal__close").click();
  });
  var address;
</script>